name: FastAPI CI

on:
  push:
    branches: [ main ]
  pull_request:
    branches: [ main ]

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout do código
        uses: actions/checkout@v3

      - name: Configurar Python
        uses: actions/setup-python@v4
        with:
          python-version: '3.10'

      - name: Instalar dependências
        run: |
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Rodar Lint (flake8)
        run: |
          flake8 .

      - name: Verificar formatação (black)
        run: |
          black --check .

      - name: Rodar testes (pytest)
        run: |
          cd ${{ github.workspace }}
          python -m pytest tests/ -v
